### ISSUE TITLE
Add keyword system to sources

### ISSUE THREAD

**Issue by mukrop** [pancelka/diplomova_laska#10]
Add a keyword system to exercises: Commented lines with hashtag words? Or keyword per line? Python/Bash magic to sort these fo TeX before compilation?

**Comment by yaqwsx** [comment]
Prepared in 017eee2e2c6bac4cf21313f26d0a0dd98634c347. What needs to be done:
- [x] tag the rest of the assignments (@pancelka)
- [x] sort the tags on the problems page
- [x] link the problems page from the title page
