### ISSUE TITLE
Unify enumerate styles

### ISSUE THREAD

**Issue by pancelka** [pancelka/diplomova_laska#12]
Some of the lists are in the form a), b), c); some in the form a., b., c. The first one is the preferred one. 

a., b., c. occur in:
* seminar02: problems 45 and 46
* seminar07: problem 63-I-5-N3
* seminar12: problems 64-II-3, 65-I-4
* seminar18: problem 61-I-4
* seminar21: problem 64-II-1
* seminar25: problem 66-II-2
* seminar29: solution of the problem B-58-I-2
* seminar30: problems B-59-I-6 and B-64-II-4

**Comment by yaqwsx** [comment]
Solved by c3cc107
