### ISSUE TITLE
Problems subpage adjustments

### ISSUE THREAD

**Issue by pancelka** [pancelka/diplomova_laska#15]
- [x] Add a link from the home page to the "problems" page

- [x] Set the default setting to "Nevybrať nič"

- [x] Show resources and footnotes only for chosen problems (when "Nevybrať nič" is on, there should not be any resources or footnotes)

- [ ] How difficult is it to add a button "Stiahni/ukáž zdroják" for each of the chosen problems?

- [x] Arrange tags in categories: Algebra, Teória čísel, Geometria, Rôzne

**Comment by yaqwsx** [comment]
> Show resources and footnotes only for chosen problems

This is harder to do and I prefer not to do so. A doable workaround is to show references after each task

>  Arrange tags in categories: Algebra, Teória čísel, Geometria, Rôzne

Give me the tag categories, easy to do.

>  Add a link from the home page to the "problems" page

Prepare the text, please.

**Comment by pancelka** [comment]
> > Show resources and footnotes only for chosen problems
> 
> This is harder to do and I prefer not to do so. A doable workaround is to show references after each task
> 

Then I'd prefer to have it after each task, thanks!

> > Arrange tags in categories: Algebra, Teória čísel, Geometria, Rôzne
> 
> Give me the tag categories, easy to do.
> 
> > Add a link from the home page to the "problems" page
> 
> Prepare the text, please.

Will do soon!

**Comment by yaqwsx** [comment]
Done
